### ISSUE TITLE
onResults() callback is being called twice

### ISSUE THREAD

**Issue by gavingt** [zagum/SpeechRecognitionView#14]
Set a breakpoint here and you'll notice that the callback method is now being called twice:

https://github.com/zagum/SpeechRecognitionView/blob/c45c3d5b84598337c378800c5407c93b62e7fe72/speechrecognitionview-sample/src/main/java/com/github/zagum/speechrecognitionview/sample/MainActivity.java#L63

This only started happening yesterday. I've confirmed that it happens on multiple devices.

Here's the only reference to this issue I can find online. It's a StackOverflow post from March, where this randomly started happening to them too:

https://stackoverflow.com/questions/60853257/android-recognitionlistener-onresults-being-called-twice

**Comment by yagizsenal** [comment]
Hi, I'm not developer but just a user of this project. However, I would like to inform you that this issue is not related with SpeechRecognitionView. It is caused by Android Speech Recognition Service.

**Comment by gavingt** [comment]
@yagizsenal Fair enough. Do you have any other information about it?

**Comment by yagizsenal** [comment]
In regard of this issue, no. If you look for a solution, I have a hacky way for it. I managed the solve the issue by checking if any two results are the same and dismiss one result if they are.

**Comment by gavingt** [comment]
I'm implemented a similar fix. The only minor issue is that I can sometimes hear the "beep" sound that accompanies the onResults callback play twice. Usually the beeps are right on top of one another, but sometimes the second lags behind the first and you hear both.

**Comment by gavingt** [comment]
Here's the Issue Tracker link for this:
https://issuetracker.google.com/issues/152628934

Google is now on it.

**Comment by zagum** [comment]
@gavingt thanks for information
