### ISSUE TITLE
How does this work with Microsoft Cognitive services speech sdk

### ISSUE THREAD

**Issue by manideeppabba1991** [zagum/SpeechRecognitionView#15]
Could you please help me understand either how to create a new one for "Microsoft Cognitive services speech sdk" or make this current solution compatible with "Microsoft Cognitive services speech sdk" ?

I see that your solution is based on 
1. android.speech.RecognitionListener
2. android.speech.SpeechRecognizer

I am looking for a solution based on "android.media.MediaRecorder"

**Comment by zagum** [comment]
Sorry, but this lib was based on android.speech.SpeechRecognizer only
