### ISSUE TITLE
Resizing View

### ISSUE THREAD

**Issue by MohamedAymenHADDAD** [zagum/SpeechRecognitionView#7]
<com.github.zagum.speechrecognitionview.RecognitionProgressView
            android:id="@+id/recognition_animation"
            **android:layout_width="42dp"
            android:layout_height="42dp"**
            android:layout_centerHorizontal="true"/>

As you can notice I am trying to resize the view with a given height and width, however this won't work. is there away to get it done, or should we wait for a new release. 

Thank you.

**Comment by zagum** [comment]
added methods in v 1.2 to set custom dimensions:

recognitionProgressView.setCircleRadiusInDp(2);
recognitionProgressView.setSpacingInDp(2);
recognitionProgressView.setIdleStateAmplitudeInDp(2);
recognitionProgressView.setRotationRadiusInDp(10);

Maybe later add autoresizing feature
