### ISSUE TITLE
Circle icon loop

### ISSUE THREAD

**Issue by princeHago** [zagum/SpeechRecognitionView#8]
[WhatsApp Video 2017-09-25 at 12.48.10.mp4.zip](https://github.com/zagum/SpeechRecognitionView/files/1347093/WhatsApp.Video.2017-09-25.at.12.48.10.mp4.zip)
Hi, i innest your addons into my app but sometimes the animation loop, like as the video.

in other case not start for listening voice...

can you help me?

Thanks in advance.

**Comment by zagum** [comment]
Can you provide your code for more information?
